# Generated by Django 3.2 on 2023-03-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purcase',
            options={'verbose_name': 'Закупка', 'verbose_name_plural': 'Закупки'},
        ),
        migrations.AlterModelOptions(
            name='values',
            options={'verbose_name': 'Данные', 'verbose_name_plural': 'Данные'},
        ),
        migrations.AlterField(
            model_name='purcase',
            name='number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='purcase',
            name='start_price',
            field=models.FloatField(verbose_name='Стартовая цена'),
        ),
        migrations.AlterField(
            model_name='values',
            name='calculation',
            field=models.FloatField(verbose_name='Расчёт'),
        ),
        migrations.AlterField(
            model_name='values',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.purcase', verbose_name='Закупка'),
        ),
    ]
