# Generated by Django 3.2 on 2023-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230318_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purcase',
            options={'ordering': ['-number'], 'verbose_name': 'Закупка', 'verbose_name_plural': 'Закупки'},
        ),
        migrations.AlterField(
            model_name='purcase',
            name='number',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='purcase',
            name='start_price',
            field=models.FloatField(null=True, verbose_name='Стартовая цена'),
        ),
        migrations.AlterField(
            model_name='values',
            name='calculation',
            field=models.FloatField(null=True, verbose_name='Расчёт'),
        ),
    ]
